### ISSUE TITLE
Some: socket labelling

### ISSUE THREAD

**Issue by firolightfog** [CoffeeVCV/CoffeeVCV#12]
It's a minor thing but anyway... Please fix socket labelling:

<img width="127" alt="image" src="https://user-images.githubusercontent.com/34127628/170441683-01ee7ef0-c0b0-4165-b1b8-4091b2d6f941.png">

Input #1 labelled as input #3 (although the output socket next to it is labelled output #1 correctly).

**Comment by CoffeeVCV** [comment]
Hello,

Thank you for you email.
I check my version on Some, and the labeling looks right, but it is a later version.
The labeling for those inputs is automatic, by VCV so it's a bit odd.
Maybe I should add more descriptive names.

Anyway, you can get the latest from Github, or once the new versions is released (in progress).

Regards

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by CoffeeVCV** [comment]
Fixed in next versions.
